name: Semantic Pull Request

on:
  workflow_call:
    secrets:
      github-token:
        description: 'GitHub token for authentication'
        required: true

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}